### ISSUE TITLE
"Challanges"

### ISSUE THREAD

**Issue by zequip** [ihabunek/isaac#1]
![capture](https://cloud.githubusercontent.com/assets/4900176/6026626/0a70b26c-abbb-11e4-9f23-420668147201.PNG)

That's a very minor issue, but also wanted to know you if you can show us how many coins do we currently have on the donation machine.

My English is shit, sorry about that.

EDIT: In case you don't see it, it's supposed to be "Challenges"

**Comment by ihabunek** [comment]
You can already see how many coins you currently have in the donation machine. It's the last row in the "Basic" column in Stats,  called "Coins donated".

Thanks for the typo report.

**Comment by zequip** [comment]
That's really weird. I thought I CTRL+F'd The word coin and it gave me no results...
Anyways, I see it now. Thanks.
