### ISSUE TITLE
Wrong descriptions in the "Achievements" tab

### ISSUE THREAD

**Issue by Angel429** [ihabunek/isaac#3]
I've uploaded my save game file and when I saw some achievements I realised that some of them had a wrong description, here is a list of the achievements that are wrong and their correct version:

| ID | Name | Wrong version | Proper version |
| --- | --- | --- | --- |
| 69 | Platinum God | Collect all items in the game and unlock all secrets and endings minus "the soul" and its 5 unlockable items | Collect all items in the game, unlock all of the secrets and Endings minus "The Lost" and his 7 unlockable items |
| 95 | Rune of Berkano | Beat Challenge #7 | Beat Challenge #20 |
| 105 | Missing No. | Beat Challenge #20 | Beat Boss Rush with Lazarus |
| 120 | Suicide King | Beat Boss Rush with Lazarus | Beat challenge #7 |

All of this came because I was seeing my save game and I realised that the achievement "Missing No." wasn't unlocked and [the web page](http://isaac.bezdomni.net/) said that I hadn't completed Challenge #20, even when in the tab of "Challenges" it appears as "Completed" [Link to save game](http://isaac.bezdomni.net/show/714b4673af5dcb83b410b2538f605ee2)
P.S: Sorry if there is any gramatical or syntactical mistake, my english is a bit bad

**Comment by ihabunek** [comment]
Fixed thanks to @Blupi
